### PR TITLE
357 fix helper error

### LINKED ISSUE #357: {{if}} helper gets error for component syntax
```
      {{if (or logout.isRunning (not session.isAuthenticated)) "Logging Out..." "Log Out"}}
```

results in the following errors:
```
  8:11  error  Incorrect indentation of positional param 'undefined' beginning at L8:C11. Expected 'undefined' to be indentation at an of 8 but was found at 11  attribute-indentation
  8:63  error  Incorrect indentation of positional param 'Logging Out...' beginning at L8:C63. Expected 'Logging Out...' to be indentation at an of 8 but was found at 63  attribute-indentation
  8:80  error  Incorrect indentation of positional param 'Log Out' beginning at L8:C80. Expected 'Log Out' to be indentation at an of 8 but was found at 80  attribute-indentation
  8:89  error  Incorrect indentation of close curly braces '}}' for the component '{{if}}' beginning at L8:C89. Expected to be indentation at L2:C6 with an of 6 but was found at 89  attribute-indentation
```

but `if` is a helper in this context and is not a component. Breaking this out into
```
      {{#if (or logout.isRunning (not session.isAuthenticated))}}
        Logging Out
      {{else}}
        Log out
      {{/}}
```
gets rid of all lint errors.

I'm using version `0.8.14` on `ember-cli` version `2.16.2`, and using the following `.template-lintrc.js`:
```
module.exports = {
  // https://github.com/rwjblue/ember-template-lint/blob/master/lib/config/recommended.js
  extends: 'recommended',

  rules: {
    // enforces double quotes!
    'quotes': 'double',

    // attribute indentation forces multiline attributes when they exceed 80 characters
    'attribute-indentation': true,

    // eol-last (always) enforces files end with new lines
    'eol-last': 'always',

    'no-trailing-spaces': true,

    // ensures tables are inserted with thead/tbody to avoid Glimmer issues
    'table-groups': true,
  }
}
```

### PR DESCRIPTION
**Pull request by FalkF**
- #### validateCloseBrace can give an exact location
- #### fix error messages:
```
Incorrect indentation of positional param 'undefined' beginning at L8:C11. Expected 'undefined' to be indentation at an of 8 but was found at 11  attribute-indentation
Incorrect indentation of positional param 'Logging Out...' beginning at L8:C63. Expected 'Logging Out...' to be indentation at an of 8 but was found at 63  attribute-indentation
Incorrect indentation of positional param 'Log Out' beginning at L8:C80. Expected 'Log Out' to be indentation at an of 8 but was found at 80  attribute-indentation
Incorrect indentation of close curly braces '}}' for the component '{{if}}' beginning at L8:C89. Expected to be indentation at L2:C6 with an of 6 but was found at 89  attribute-indentation

```

```
Incorrect indentation of positional param 'or' beginning at L1:C5. Expected 'or' to be at L2:C2.
Incorrect indentation of positional param 'Logging Out...' beginning at L1:C57. Expected 'Logging Out...' to be at L3:C2.
Incorrect indentation of positional param 'Log Out' beginning at L1:C74. Expected 'Log Out' to be at L4:C2.
Incorrect indentation of close curly braces '}}' for the component '{{if}}' beginning at L1:C83. Expected '{{if}}' to be at L5:C0.
```

closes #357

### CODE REVIEW

File: test/unit/rules/lint-attribute-indentation-test.js [hunk 1]
```diff
@@ -225,10 +240,41 @@ generateRuleTests({
...
+    }, {
+      'column': 74,
+      'line': 1,
+      'message': 'Incorrect indentation of positional param \'Log Out\' beginning at L1:C74. Expected \'Log Out\' to be at L4:C2.',
+      'moduleId': 'layout.hbs',
+      'source': '{{if (or logout.isRunning (not session.isAuthenticated)) "Logging Out..." "Log Out"}}'
+    }, {
+      'column': 83,
+      'line': 1,
+      'message': 'Incorrect indentation of close curly braces \'}}\' for the component \'{{if}}\' beginning at L1:C83. Expected \'{{if}}\' to be at L5:C0.',
```
Comment (jasonworden) [inline test/unit/rules/lint-attribute-indentation-test.js]: should say `for the helper` not `for the component`

**Comment by jasonworden** [comment]
@FalkF 🙏 thank u!!

File: test/unit/rules/lint-attribute-indentation-test.js (hunk 1 above)
Comment (rwjblue) [reply test/unit/rules/lint-attribute-indentation-test.js]: We don’t really have a way to determine if it is a helper or component.

**Comment by rwjblue** [comment]
Thank you!!!
