### PR TITLE
Check indentation of else block too

### LINKED ISSUE #272: indentation is not tested correctly for the else block
The following code complains about the "baz" text not being indented correctly, but it does not complain that the `{{bar}}` block is indented incorrectly.
```
{{#if foo}}
  foo
{{else}}
    {{#bar}}
    baz
    {{/bar}}
{{/if}}
```

### PR DESCRIPTION
**Pull request by initram**
Make sure that the else-block is also returned from the childrenFor, so that they can be tested for indentation.

Fixes #272

### CODE REVIEW

File: lib/helpers/ast-node-info.js [hunk 1]
```diff
@@ -66,6 +66,9 @@ function childrenFor(node) {
     return node.body;
   }
   if (node.type === 'BlockStatement') {
+    if(node.inverse){
+      return node.program.body.concat(node.inverse.body);
```
Comment (rwjblue) [inline lib/helpers/ast-node-info.js]: I believe that its possible to only have an inverse (and therefore `node.program.body` is null/undefined).

Perhaps something like this might work:

```js
return [].concat(
  node.program && node.program.body,
  node.inverse && node.inverse.body
).filter(Boolean);
```

Comment (initram) [reply lib/helpers/ast-node-info.js]: Do you have an example of this? then I would be able to add that to the test suite.

Comment (rwjblue) [reply lib/helpers/ast-node-info.js]: I think this will do it:

```hbs
{{#unless}}
{{/unless}}
```

Comment (initram) [reply lib/helpers/ast-node-info.js]: Okay, I will try that tomorrow. 
It looks like it should only be inverse that is nullable here: https://github.com/glimmerjs/glimmer-vm/blob/e8eb555378f2699676cf39a11fc6dc96af847b58/packages/%40glimmer/syntax/lib/types/nodes.ts#L47

Comment (rwjblue) [reply lib/helpers/ast-node-info.js]: ya, agreed

I just did a quick test on astexplorer.net and it seems that program is populated there also, so maybe it just isn't possible?

Comment (initram) [reply lib/helpers/ast-node-info.js]: I have not been able to produce a BlockStatement without a `program`. I do not this it is possible, which would also make sense when looking at the typescript definition.
But if you still prefer a null check for the possibility that it may sneak in later, then just let me know.

Comment (rwjblue) [reply lib/helpers/ast-node-info.js]: Nope, seems fine to me. Thank you for digging into this!

**Comment by rwjblue** [comment]
Will merge and release shortly....
